### ISSUE TITLE
reset password is broken

### ISSUE THREAD

**Issue by bertBruynooghe** [mcasimir/devise-i18n-views#105]
version 0.3.7
devise 4.1.1

Create a [brand new rails project](https://github.com/bertBruynooghe/type_one_too) last week, including devise, devise-i18n and devise-i18n-views out of the box, nl as locale.

Resetting the password in the app gives me: 

> Reset password token is ongeldig.

When removing devise-i18n-views, the problem does not occur.

**Comment by bertBruynooghe** [comment]
also works when I downgrade devise to '~>3.x' (3.5.10)

**Comment by JasonBarnabe** [comment]
> devise-i18n-views has been merged into devise-i18n. You should stop using devise-i18n-views and start using devise-i18n 1.0.0 or later. There will be no further releases of devise-i18n-views.
