### ISSUE TITLE
Bootstrap views

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [mcasimir/devise-i18n-views#64]
You really have to add the Twitter Bootstrap and/or Foundation templates.

**Comment by yanyingwang** [comment]
@Yachtsman @JasonBarnabe  OK, guys, very boring to edit the views, but for the rest of world, there is a new PR  mcasimir/devise-i18n-views#72  added by me. After merged it, we could use this cmd: `rails g devise:views:i18n_templates:slim_simple_form_foundation` to generate devise view templates written compat [slim](https://github.com/slim-template/slim-rails) [simple_form](https://github.com/plataformatec/simple_form) and [foundation](https://github.com/zurb/foundation-rails).

**Comment by joel** [comment]
@Yachtsman @JasonBarnabe I've added a [PR for bootstrap](https://github.com/mcasimir/devise-i18n-views/pull/85)

@mcasimir please consider thus 2 PRs to merge on master or at least leave comment on what is not good and what we need to change for these PRs can be mergeable for you.

**Comment by JasonBarnabe** [comment]
This project is being merged into [devise-i18n](https://github.com/tigrish/devise-i18n). Please make all further contributions there.
