### ISSUE TITLE
Input labels

### ISSUE THREAD

**Issue by nikue** [mcasimir/devise-i18n-views#70]
Maybe I'm missing something, but shouldn't form input labels also be translated?

**Comment by JasonBarnabe** [comment]
Which labels are you referring to?

**Comment by nikue** [comment]
Well, just for example:

Original:

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

Modified:

  <div><%= f.label :email, t(:email) %><br />
  <%= f.email_field :email %></div>

Otherwise all the labels appear in English regardless of locale, no?

**Comment by JasonBarnabe** [comment]
No, [`label` will translate](http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-label) it to [the appropriate language](https://github.com/mcasimir/devise-i18n-views/blob/master/locales/zh-CN.yml#L6).

**Comment by nikue** [comment]
Ah, I was indeed missing something. Thanks!

Nikue Gardner
