### ISSUE TITLE
registrations#new view is not translated

### ISSUE THREAD

**Issue by nyjt** [mcasimir/devise-i18n-views#75]
Is there any reason that this file is not translated?
https://github.com/mcasimir/devise-i18n-views/blob/master/app/views/devise/registrations/new.html.erb

**Comment by nyjt** [comment]
```Password``` and ```Remeber me``` also should be translated.
https://github.com/maximalink/devise3-i18n-views/blob/master/app/views/devise/sessions/new.html.erb

**Comment by JasonBarnabe** [comment]
What makes you think they're not translated?

**Comment by nyjt** [comment]
```Password confirmation``` label
https://github.com/mcasimir/devise-i18n-views/blob/master/app/views/devise/registrations/new.html.erb#L12

and 

```Password``` label
https://github.com/mcasimir/devise-i18n-views/blob/master/app/views/devise/registrations/new.html.erb#L9

**Comment by JasonBarnabe** [comment]
Read about localization at http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-label.

This is [translatable](https://github.com/mcasimir/devise-i18n-views/blob/master/locales/en.yml#L62) but perhaps not yet provided in [the language you care about](https://github.com/mcasimir/devise-i18n-views/blob/master/locales/hu.yml#L4)?

**Comment by nyjt** [comment]
Thanks. I think inline translation would be better instead of ActiveRecord translation in this case. Devise support any name for resource. If somebody generate member, client, staff, or other this current translation method will not work.

Another reason is DRY. These attributes are not model name specific. For example the password is the same for client, staff, member, user, now we need to translate for all generated model. Why we need to translate more than once?

**Comment by JasonBarnabe** [comment]
That sounds pretty uncommon - a more reasonable scenario would be to have a user model and either attributes defining their role or submodels.

You can always generate the views and locales and customize away.
