### ISSUE TITLE
Need to add minimum password length hint translation

### ISSUE THREAD

**Issue by nyjt** [mcasimir/devise-i18n-views#77]
I think registrations#new view should be extended with password minimum length hint according to this part of devise view: https://github.com/plataformatec/devise/blob/master/app/views/devise/registrations/new.html.erb#L13-L15

What do you think?

**Comment by JasonBarnabe** [comment]
I'm guessing this is something fairly new. If it can be added without breaking older versions of devise, yes, it should be added.

**Comment by JasonBarnabe** [comment]
This project is being merged into [devise-i18n](https://github.com/tigrish/devise-i18n). Please make all further contributions there.
