### ISSUE TITLE
Errno::EACCES: Permission denied

### ISSUE THREAD

**Issue by adilsoncarvalho** [mcasimir/devise-i18n-views#80]
Right after installing the gem I got this error white trying to use it.

```
I18n::InvalidLocaleData at /users/sign_in
can not load translations from /home/vagrant/.rvm/gems/ruby-2.2.2/gems/devise-i18n-views-0.3.4/lib/../locales/pt-BR.yml: #<Errno::EACCES: Permission denied @ rb_sysopen - /home/vagrant/.rvm/gems/ruby-2.2.2/gems/devise-i18n-views-0.3.4/lib/../locales/pt-BR.yml>
```

I don't know why but it is generating most of the translation files with a very restrictive permission

```
$ ll -lah /home/vagrant/.rvm/gems/ruby-2.2.2/gems/devise-i18n-views-0.3.4/lib/../locales/
total 124K
drwxr-xr-x 2 root root 4.0K Jul  3 02:47 ./
drwxr-xr-x 6 root root 4.0K Jul  3 02:47 ../
-rw------- 1 root root 3.8K Jul  3 02:47 bg.yml
-rw------- 1 root root 2.9K Jul  3 02:47 ca.yml
-rw------- 1 root root 2.7K Jul  3 02:47 cs.yml
-rw------- 1 root root 2.6K Jul  3 02:47 da-DK.yml
-rw------- 1 root root 2.9K Jul  3 02:47 de.yml
-rw------- 1 root root 4.3K Jul  3 02:47 el.yml
-rw-r--r-- 1 root root 2.7K Jul  3 02:47 en.yml
-rw------- 1 root root 2.5K Jul  3 02:47 es-AR.yml
-rw------- 1 root root 2.9K Jul  3 02:47 es-ES.yml
-rw------- 1 root root 3.0K Jul  3 02:47 es-MX.yml
-rw------- 1 root root 2.9K Jul  3 02:47 es.yml
-rw------- 1 root root 2.5K Jul  3 02:47 fi.yml
-rw------- 1 root root 2.9K Jul  3 02:47 fr.yml
-rw------- 1 root root 2.8K Jul  3 02:47 hu.yml
-rw------- 1 root root 2.6K Jul  3 02:47 it.yml
-rw------- 1 root root 3.3K Jul  3 02:47 ja.yml
-rw------- 1 root root 2.5K Jul  3 02:47 nb.yml
-rw------- 1 root root 2.8K Jul  3 02:47 nl.yml
-rw------- 1 root root 2.7K Jul  3 02:47 pl.yml
-rw------- 1 root root 2.7K Jul  3 02:47 pt-BR.yml
-rw------- 1 root root 2.5K Jul  3 02:47 pt-PT.yml
-rw------- 1 root root 3.5K Jul  3 02:47 ru.yml
-rw------- 1 root root 2.8K Jul  3 02:47 sk.yml
-rw------- 1 root root 4.6K Jul  3 02:47 th.yml
-rw------- 1 root root 2.7K Jul  3 02:47 tr.yml
-rw-r--r-- 1 root root 2.6K Jul  3 02:47 zh-CN.yml
-rw------- 1 root root 2.5K Jul  3 02:47 zh-TW.yml
```

Any ideas?

**Comment by JasonBarnabe** [comment]
Those match the permissions that I see, but I suppose the difference is you installed the gem as root and your web server is not running as root.

I'd be willing to change the permissions if someone could point out what is typical for stuff like this.

**Comment by djmaze** [comment]
@JasonBarnabe: In short, this is the case I am encountering when deploying projects using distinct project users: Each project has its own user and group on the server. We have a distinct user on the server for everyone who is allowed to deploy. The user is a member of each project's group so he can write files to the project's directories. Files get deployed as `myusername:project` with permission `rw-rw-r--`. 

The webserver then runs as user `www-data` with read access. So we need the `o+r` permission set (and `o+rx` for directories). As this is the default when installing most gems, I think this should be the case in this gem, too.

**Comment by djmaze** [comment]
Update: The webserver (passenger) runs as the `project` user, so the files have to be at least group readable.

**Comment by Dschee** [comment]
Similar Issue for me, see: https://github.com/mcasimir/devise-i18n-views/issues/86

Although I can implement a workaround by changing the permissions of the gems directory on each deploy this would be really hacky and therefore a cleaner solution within this gem would be great to see!

**Comment by Dschee** [comment]
As a workaround I wrote a small script that changes the permissions for the gems locales directory. This is not a good solution though as it depends on both the **ruby version** and the **gem version** – but it's working for now and I hope it's going to be fixed in future versions anyway so I can remove it.

You can find the script here:
https://github.com/Flinesoft/MovieAssistor/blob/25c3030a36381e1bb10f2ab17c4f19e99a6cf4a0/.cloud66/deploy_hooks.yml

**Comment by JasonBarnabe** [comment]
I did some stuff and maybe fixed it. When I uninstall and install from the repo I see directories with 755 and files with 644.

Or maybe this only affected the packaged gem. In that case it will be fixed now that I fixed it locally.

**Comment by Dschee** [comment]
I just deployed and it seems to be working for me without the workaround now. But I also changed my server environment in the meantime so that might have also been the reason it's working. What about @djmaze or @adilsoncarvalho, is it working for you guys now?

**Comment by djmaze** [comment]
@Dschee, Tried removing and reinstalling 0.3.4 (through bundler). Unfortunately, the problem remains for me.

**Comment by Dschee** [comment]
@djmaze: Version 0.3.4 doesn't include @JasonBarnabe's changes yet, have you tried installing the master?

I'm doing it like this and it's working:
``` ruby
gem 'devise-i18n-views', github: 'mcasimir/devise-i18n-views', branch: :master
```

**Comment by djmaze** [comment]
@Dschee Right, the master version is working. But I am not sure if it's because of the changes or rather that I am using the code from the git repository instead of from the gem. I think the gem packaging is the problem here, right?

**Comment by Dschee** [comment]
I'm not sure, but @JasonBarnabe states that it should be fixed now for the packaged gem too. I think we need him to upload a new version first to try that out and clarify for sure.

**Comment by JasonBarnabe** [comment]
I've released 0.3.5. Does it fix the issue?

**Comment by Dschee** [comment]
@JasonBarnabe: Looks good here, just updated the project and it doesn't show any errors any more. Thank you very much!

**Comment by djmaze** [comment]
Yeah, thank you @JasonBarnabe, it works now!
