### ISSUE TITLE
Ukrainian locale should named just :uk

### ISSUE THREAD

**Issue by valdemarua** [mcasimir/devise-i18n-views#91]
For example, there is no uk-UA locale in rails-i18n:

Available locales are:

    af, ar, az, bg, bn, bs, ca, cs, cy, da, de, de-AT, de-CH, el, en, en-AU, en-CA, en-GB, en-IE, en-IN, en-NZ, en-US, en-ZA, eo, es, es-419, es-AR, es-CL, es-CO, es-CR, es-EC, es-MX, es-PA, es-PE, es-US, es-VE, et, eu, fa, fi, fr, fr-CA, fr-CH, gl, he, hi, hi-IN, hr, hu, id, is, it, it-CH, ja, km, kn, ko, lo, lt, lv, mk, mn, mr-IN, ms, nb, ne, nl, nn, or, pl, pt, pt-BR, rm, ro, ru, sk, sl, sr, sv, sw, ta, th, tl, tr, tt, uk, ug, ur, uz, vi, wo, zh-CN, zh-HK, zh-TW, zh-YUE

https://github.com/svenfuchs/rails-i18n

**Comment by JasonBarnabe** [comment]
Neither does [devise-i18n](https://github.com/tigrish/devise-i18n/tree/master/rails/locales). Makes sense to me.

**Comment by valdemarua** [comment]
Thank you :+1:
